### ISSUE TITLE
mongoose error

### ISSUE THREAD

**Issue by abhinavsri360** [abhinavsri360/comblog-new#3]
message: 'The `uri` parameter to `openUri()` must be a string, got ' +
    '"undefined". Make sure the first parameter to ' +
    '`mongoose.connect()` or `mongoose.createConnection()` is ' +
    'a string.',
  name: 'MongooseError'

The above message pops up on console :)
to run the application do run the following
npm install
npm start

**Comment by Troy96** [comment]
Hi @abhinavsri360 ,

Can I fix this up?

**Comment by abhinavsri360** [comment]
Yeah sure why not, go ahead. @Troy96

**Comment by Troy96** [comment]
Cool, thanks.

**Comment by abhinavsri360** [comment]
#6 Fixes this, closing thereafter.
